# Generated by Django 2.2.2 on 2019-06-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='rate',
            new_name='exchange_rate',
        ),
    ]
