# Generated by Django 2.2.2 on 2019-06-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20190613_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
