# Generated by Django 2.2.2 on 2019-06-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20190613_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
