# Generated by Django 2.2.2 on 2019-06-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_auto_20190614_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate',
            field=models.FloatField(max_length=5),
        ),
    ]
