# Generated by Django 2.2.2 on 2019-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_auto_20190614_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
