# Generated by Django 2.2.2 on 2019-06-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_auto_20190614_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, default=1.1, max_digits=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
