# Generated by Django 2.2.2 on 2019-06-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_auto_20190615_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
