# Generated by Django 2.2.2 on 2019-06-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0012_auto_20190617_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
