# Generated by Django 2.2.4 on 2019-08-02 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0014_auto_20190802_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='valid_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
