# Generated by Django 2.2.4 on 2019-08-06 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0015_exchangerate_valid_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'exchange rate', 'verbose_name_plural': 'exchange rates'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(max_length=5, unique=True, verbose_name='iso code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='converter.Currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='valid_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='valid date'),
        ),
    ]
