# Generated by Django 2.2.4 on 2019-08-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0018_auto_20190807_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'permissions': [('update_currencies', 'user can update currencies')], 'verbose_name': 'exchange rate', 'verbose_name_plural': 'exchange rates'},
        ),
    ]
