# Generated by Django 2.2.4 on 2019-08-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0019_auto_20190808_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'exchange rate', 'verbose_name_plural': 'exchange rates'},
        ),
    ]
