# Generated by Django 2.2.4 on 2019-08-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0021_auto_20190808_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'permissions': [('update_exchange_rates', 'user can update exchange rates')], 'verbose_name': 'exchange rate', 'verbose_name_plural': 'exchange rates'},
        ),
    ]
