# Generated by Django 2.2.4 on 2019-08-09 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0022_auto_20190809_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='valid_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='valid date'),
        ),
    ]
